/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_asnaandiaauladi_1855201082;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Andi
 */
public class datasantri extends javax.swing.JFrame {

    /**
     * Creates new form administrator_kasir
     */
    public datasantri() {
        initComponents();
        this.setTitle("aplikasi database toko");
        this.setLocationRelativeTo(this);
        koneksi konek = new koneksi();
        konek.koneksi();
        status.setText(konek.koneksis);
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        in_ns = new javax.swing.JTextField();
        ad_simpan = new javax.swing.JButton();
        in_alm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        in_ang = new javax.swing.JTextField();
        in_jns = new javax.swing.JTextField();
        ad_hapus = new javax.swing.JButton();
        ad_cari = new javax.swing.JButton();
        ad_update = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        in_nm = new javax.swing.JTextField();
        pilih = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adm_tabel = new javax.swing.JTable();
        in_resert = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        in_ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nsActionPerformed(evt);
            }
        });

        ad_simpan.setBackground(new java.awt.Color(255, 0, 51));
        ad_simpan.setText("SIMPAN");
        ad_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_simpanActionPerformed(evt);
            }
        });

        in_alm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_almActionPerformed(evt);
            }
        });

        jLabel1.setText("NAMA SANTRI");

        jLabel2.setText("ALAMAT");

        jLabel3.setText("JENIS KELAMIN");

        jLabel4.setText("ANGKATAN");

        in_ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_angActionPerformed(evt);
            }
        });

        in_jns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_jnsActionPerformed(evt);
            }
        });

        ad_hapus.setBackground(new java.awt.Color(255, 0, 51));
        ad_hapus.setText("HAPUS");
        ad_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_hapusActionPerformed(evt);
            }
        });

        ad_cari.setBackground(new java.awt.Color(255, 0, 51));
        ad_cari.setText("CARI");
        ad_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_cariActionPerformed(evt);
            }
        });

        ad_update.setBackground(new java.awt.Color(255, 0, 51));
        ad_update.setText("ubah");
        ad_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_updateActionPerformed(evt);
            }
        });

        status.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMOR SANTRI");

        in_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_nmActionPerformed(evt);
            }
        });

        pilih.setBackground(new java.awt.Color(255, 0, 51));
        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih pencarian-", "nomor santri", "nama santri", "alamat", "jeniskelamin", "angkatan" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pilih, javax.swing.GroupLayout.Alignment.LEADING, 0, 360, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_ns, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_alm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_jns, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_ang, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(ad_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ad_simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ad_hapus))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ad_update, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(in_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_alm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_jns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(in_ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_hapus)
                    .addComponent(ad_simpan)
                    .addComponent(ad_cari)
                    .addComponent(ad_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        adm_tabel.setBackground(new java.awt.Color(0, 255, 255));
        adm_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nomorsantri", "namasantri", "alamat", "jeniskelamin", "angkatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adm_tabel.setGridColor(new java.awt.Color(0, 0, 0));
        adm_tabel.setSelectionBackground(new java.awt.Color(204, 255, 255));
        adm_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adm_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adm_tabel);

        in_resert.setBackground(new java.awt.Color(255, 0, 51));
        in_resert.setText("resert");
        in_resert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_resertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(in_resert)
                .addGap(190, 190, 190))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(in_resert)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("administrator");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectBynm(int nm) throws SQLException {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datasantri where nomorsantri like '%" + nm + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByns(String ns) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datasantri where namasantri like '%" + ns + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByalm(String alm) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datasantri where alamat like '%" + alm + "%'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByjns(String jns) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datasantri where jeniskelamin like '" +jns+ "'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void selectByang(int ang) {
        koneksi konek = new koneksi();
        konek.koneksi();

        try {
            String sql = "select * from datasantri where angkatan like '" + ang + "'";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

//    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
//        
//        // TODO add your handling code here:
//    }                                    
    Statement pst;
    ResultSet rs;

    public void table() {
        koneksi konek = new koneksi();
        konek.koneksi();
        try {
            String sql = "select * from datasantri";
            pst = konek.con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            adm_tabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void in_nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nsActionPerformed

    private void in_almActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_almActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_almActionPerformed

    private void in_angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_angActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_angActionPerformed

    private void in_jnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_jnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_jnsActionPerformed

    private void ad_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_cariActionPerformed
        if (pilih.getSelectedIndex() == 1) {

            try {
                selectBynm(Integer.parseInt(in_nm.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(datasantri.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (pilih.getSelectedIndex() == 2) {
            selectByns(in_ns.getText());
        } else if (pilih.getSelectedIndex() == 3) {
            selectByalm(in_alm.getText());
        } else if (pilih.getSelectedIndex() == 4) {
            selectByjns(in_jns.getText());

        } else if (pilih.getSelectedIndex() == 5) {
            selectByang(Integer.parseInt(in_ang.getText()));

        } else {
            table();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ad_cariActionPerformed

    private void ad_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_updateActionPerformed
        // TODO add your handling code here:
        koneksi konek = new koneksi();
        konek.koneksi();

        update ubah = new update();
        String ns = in_ns.getText();
        String nm = in_nm.getText();
        String alm = in_alm.getText();
        String ang = in_ang.getText();
        String jns = in_jns.getText();

        ubah.update(Integer.parseInt(nm), ns,alm, jns, Integer.parseInt(ang));

        table();
    }//GEN-LAST:event_ad_updateActionPerformed

    private void ad_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_simpanActionPerformed
        insert in = new insert();
        int nm = Integer.parseInt(in_nm.getText());
        String ns = in_ns.getText();
        int ang = Integer.parseInt(in_ang.getText());
        String jns = in_jns.getText();
        String alm = in_alm.getText();
        in.insert(nm, ns, alm, jns, ang);

        table();

        // TODO add your handling code here:
    }//GEN-LAST:event_ad_simpanActionPerformed

    private void adm_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adm_tabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) adm_tabel.getModel(); //create a model
        int selectedRowIndex = adm_tabel.getSelectedRow(); //get selected row
        int id = (int) dtm.getValueAt(selectedRowIndex, 0); //get the primary key to fetch data.

        koneksi konek = new koneksi();
        konek.koneksi();

        try {

            String sql = "select * from datasantri where nomorsantri like '%" + id + "%'";
            pst = (Statement) konek.con.prepareStatement(sql);
            ResultSet rs = rs = pst.executeQuery(sql);

            while (rs.next()) {    //u can use normal query
                in_nm.setText(rs.getString("nomorsantri"));
                in_ang.setText(rs.getString("angkatan"));
                in_alm.setText(rs.getString("alamat"));
                in_ns.setText(rs.getString("namasantri"));
                in_jns.setText(rs.getString("jeniskelamin"));
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_adm_tabelMouseClicked

    private void in_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_nmActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ad_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_hapusActionPerformed
        koneksi konek = new koneksi();
        konek.koneksi();

        delete del = new delete();
        del.delete(Integer.parseInt(in_nm.getText()));

        table();
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_hapusActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
     
    }//GEN-LAST:event_jLabel7MouseClicked

    private void in_resertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_resertActionPerformed
        // TODO add your handling code here:
        in_nm.setText("");
        in_ang.setText("");
        in_alm.setText("");
        in_ns.setText("");
        in_jns.setText("");

        table();
    }//GEN-LAST:event_in_resertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datasantri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad_cari;
    private javax.swing.JButton ad_hapus;
    private javax.swing.JButton ad_simpan;
    private javax.swing.JButton ad_update;
    private javax.swing.JTable adm_tabel;
    private javax.swing.JTextField in_alm;
    private javax.swing.JTextField in_ang;
    private javax.swing.JTextField in_jns;
    private javax.swing.JTextField in_nm;
    private javax.swing.JTextField in_ns;
    private javax.swing.JButton in_resert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
